### ISSUE TITLE
关于部分的重复造轮子建议

### ISSUE THREAD

**Issue by htrlq** [Coldairarrow/Colder.Fx.Core.AdminLTE#1]
无论是分布式Session还是缓存切换，都可以在实现IDistributedCache里面解决~Session本身就支持分布式，核心是加密和分布式缓存，默认实现是自身内存而已。把缓存替换成Redis即可，微软已实现了基于Redis的分布式缓存，Session直接无感知替换成分布式，基于其他Nosql或者缓存中间件都一样的小代价改造。
缓存切换只需要依赖于IDistributedCache写一组接口，接口内置扩展方法，依赖注入这个接口即可。

**Comment by alexinea** [comment]
去微软化是社区之幸。
