### ISSUE TITLE
代码生成没有表

### ISSUE THREAD

**Issue by tiger2014** [Coldairarrow/Colder.Fx.Core.AdminLTE#4]
链接字符串为：
![image](https://user-images.githubusercontent.com/6703612/54452998-9f0eaa80-4713-11e9-9a19-f0dca4f3d23a.png)

但是，点击“代码生成”时，出现，无表的情况：

![image](https://user-images.githubusercontent.com/6703612/54453059-bcdc0f80-4713-11e9-87a4-77d278c58405.png)

请问怎么处理？

**Comment by Coldairarrow** [comment]
请进群反馈详情
