### ISSUE TITLE
作者使用的redis是哪个版本，我使用redis5出现错误

### ISSUE THREAD

**Issue by rewatn** [Coldairarrow/Colder.Fx.Core.AdminLTE#5]
我使用win10-1809版本，docker for  windows 安装的redis，提示错误
![image](https://user-images.githubusercontent.com/21985953/54469903-0858f100-47da-11e9-9d0b-24e39beecebf.png)

**Comment by Godricm** [comment]
docker中的redis有没有把端口暴露出来
